### ISSUE TITLE
Unable to close the side bar on menu buttons and redirect to new page 

### ISSUE THREAD

**Issue by MayankAgarwal04** [andreybuksha/LMCSideMenu#1]
@andreybuksha 
we have implemented the code as suggested by you . We are facing below issues :
-  Not able to close the side bar on item1/item2 click.
- Not able to redirect to new page

**Comment by andreybuksha** [comment]
Hello. Could you provide the simplified sample of your implementation, specifically how are you trying to close the menu

**Comment by MayankAgarwal04** [comment]
we have used the same code as you have provided. But we need to close the side bar on some 
action button. In your code when we click on items (items in side bar), side bar is not closing

**Comment by MayankAgarwal04** [comment]
All methods and variables are made private and internal. we are unable to access

**Comment by andreybuksha** [comment]
that's because closing is not displayed at the moment in sample project.
To close the menu you should simply call dismiss method on your menu controller. For example, with the sample it could be like this:

```
class RightMenuController: UITableViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        dismiss(animated: true, completion: nil)
    }

}
```
But you probably want to add some logic in `didSelectRowAt` method to distinguish what row was tapped

**Comment by kedar1988** [comment]
We want to navigate to new screen on "didSelectRowAt" method. I meant want to push new VC from centerViewcontroller on tap of didSelectRowAt

**Comment by andreybuksha** [comment]
You can use different approaches here. But basically you need to notify center view controller when it needs to present/push new vc after menu is dismissed. 
It could be delegates, notifications or just accessing presenting view controller. 
In my own project I use delegates, and call delegate in completion of dismissed method.
Like so:

```
weak var delegate: RightMenuDelegate?

override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        dismiss(animated: true) { [weak self] in
            self?.delegate?.onPresentVC()
        }
    }
```

That's just one way of presenting, you can choose whatever approach is more suitable for you

**Comment by kedar1988** [comment]
@andreybuksha Thanks a lot. I also using delegate, as you mentioned. Let me check once.

**Comment by andreybuksha** [comment]
ok, I will close the issue. Feel free to reopen if you have any questions
